// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2008
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.1.136 (2008-11-11)
// Machine:  macbook-pro-stas.local
// DateTime: 03.06.2011 0:09:18
// UserName: Stas
// Input file <L1Parser.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Text;
using gppg;
using L1Specializer.SyntaxTree;
using L1Specializer.SyntaxTree.IfStatements;
using L1Specializer.Metadata;
using L1Runtime.SyntaxTree;

namespace L1Specializer
{
public enum Tokens {
    error=1,EOF=2,INT=3,CHAR=4,BOOL=5,ARRAY=6,
    NEW=7,ARRAY_LENGTH=8,ASSERT=9,RETURN=10,DEFINE=11,END=12,
    NULL=13,T=14,F=15,WHILE=16,DO=17,TO=18,
    STEP=19,IF=20,THEN=21,ELSE=22,ELSIF=23,INTEGER=24,
    CHAR_LITERAL=25,IDENTIFIER=26,STRING_LITERAL=27,NOT=28,LP=29,RP=30,
    LAP=31,RAP=32,LFP=33,RFP=34,SEMI=35,COMMA=36,
    GOTO=37,PERIPERI=38,ILLEGAL=39,ASSIGN=40,OR=41,XOR=42,
    AND=43,EQ=44,NEQ=45,GR=46,GREQ=47,LE=48,
    LEEQ=49,PLUS=50,MINUS=51,MULT=52,DIV=53,MOD=54,
    POWER=55,UMINUS=56};

public struct ValueType
{ 
    public char cVal; 
    public int iVal; 
    public string sVal; 

    public object Tag;
}
// Abstract base class for GPLEX scanners
public abstract class ScanBase : IScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class L1Parser: ShiftReduceParser<ValueType, LexLocation>
{
    private Dictionary<int, string> aliasses = null;

  protected override void Initialize()
  {
    this.errToken = (int)Tokens.error;
    this.eofToken = (int)Tokens.EOF;

    states=new State[168];
    AddState(0,new State(new int[]{11,154},new int[]{-1,1,-4,3,-5,5}));
    AddState(1,new State(new int[]{2,2}));
    AddState(2,new State(-1));
    AddState(3,new State(new int[]{11,154,2,-4},new int[]{-1,4,-4,3,-5,5}));
    AddState(4,new State(-3));
    AddState(5,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,6,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(6,new State(new int[]{12,7}));
    AddState(7,new State(-5));
    AddState(8,new State(new int[]{36,9,12,-16,16,-16,23,-16,22,-16}));
    AddState(9,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,10,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(10,new State(-15));
    AddState(11,new State(-17));
    AddState(12,new State(new int[]{18,13}));
    AddState(13,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,14,-18,88}));
    AddState(14,new State(new int[]{17,15,19,149,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(15,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,16,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(16,new State(new int[]{12,17}));
    AddState(17,new State(-65));
    AddState(18,new State(new int[]{26,19,6,91}));
    AddState(19,new State(new int[]{40,20,35,-85,36,-85,12,-85,16,-85,23,-85,22,-85}));
    AddState(20,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,21,-18,88}));
    AddState(21,new State(new int[]{40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55,18,-67,35,-84,36,-84,12,-84,16,-84,23,-84,22,-84}));
    AddState(22,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,23,-18,88}));
    AddState(23,new State(new int[]{40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55,36,-29,12,-29,18,-29,16,-29,23,-29,22,-29,17,-29,19,-29,35,-29,32,-29,30,-29,21,-29}));
    AddState(24,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,25,-18,88}));
    AddState(25,new State(new int[]{32,26,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(26,new State(-30));
    AddState(27,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,28,-18,88}));
    AddState(28,new State(new int[]{40,-31,31,24,50,-31,51,-31,55,31,52,33,53,35,54,37,44,-31,45,-31,46,-31,47,-31,48,-31,49,-31,41,-31,43,-31,42,-31,36,-31,12,-31,18,-31,16,-31,23,-31,22,-31,17,-31,19,-31,35,-31,32,-31,30,-31,21,-31}));
    AddState(29,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,30,-18,88}));
    AddState(30,new State(new int[]{40,-32,31,24,50,-32,51,-32,55,31,52,33,53,35,54,37,44,-32,45,-32,46,-32,47,-32,48,-32,49,-32,41,-32,43,-32,42,-32,36,-32,12,-32,18,-32,16,-32,23,-32,22,-32,17,-32,19,-32,35,-32,32,-32,30,-32,21,-32}));
    AddState(31,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,32,-18,88}));
    AddState(32,new State(new int[]{40,-33,31,24,50,-33,51,-33,55,31,52,-33,53,-33,54,-33,44,-33,45,-33,46,-33,47,-33,48,-33,49,-33,41,-33,43,-33,42,-33,36,-33,12,-33,18,-33,16,-33,23,-33,22,-33,17,-33,19,-33,35,-33,32,-33,30,-33,21,-33}));
    AddState(33,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,34,-18,88}));
    AddState(34,new State(new int[]{40,-34,31,24,50,-34,51,-34,55,31,52,-34,53,-34,54,-34,44,-34,45,-34,46,-34,47,-34,48,-34,49,-34,41,-34,43,-34,42,-34,36,-34,12,-34,18,-34,16,-34,23,-34,22,-34,17,-34,19,-34,35,-34,32,-34,30,-34,21,-34}));
    AddState(35,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,36,-18,88}));
    AddState(36,new State(new int[]{40,-35,31,24,50,-35,51,-35,55,31,52,-35,53,-35,54,-35,44,-35,45,-35,46,-35,47,-35,48,-35,49,-35,41,-35,43,-35,42,-35,36,-35,12,-35,18,-35,16,-35,23,-35,22,-35,17,-35,19,-35,35,-35,32,-35,30,-35,21,-35}));
    AddState(37,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,38,-18,88}));
    AddState(38,new State(new int[]{40,-36,31,24,50,-36,51,-36,55,31,52,-36,53,-36,54,-36,44,-36,45,-36,46,-36,47,-36,48,-36,49,-36,41,-36,43,-36,42,-36,36,-36,12,-36,18,-36,16,-36,23,-36,22,-36,17,-36,19,-36,35,-36,32,-36,30,-36,21,-36}));
    AddState(39,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,40,-18,88}));
    AddState(40,new State(new int[]{40,-40,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,-40,45,-40,46,-40,47,-40,48,-40,49,-40,41,-40,43,-40,42,-40,36,-40,12,-40,18,-40,16,-40,23,-40,22,-40,17,-40,19,-40,35,-40,32,-40,30,-40,21,-40}));
    AddState(41,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,42,-18,88}));
    AddState(42,new State(new int[]{40,-41,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,-41,45,-41,46,-41,47,-41,48,-41,49,-41,41,-41,43,-41,42,-41,36,-41,12,-41,18,-41,16,-41,23,-41,22,-41,17,-41,19,-41,35,-41,32,-41,30,-41,21,-41}));
    AddState(43,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,44,-18,88}));
    AddState(44,new State(new int[]{40,-42,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,-42,45,-42,46,-42,47,-42,48,-42,49,-42,41,-42,43,-42,42,-42,36,-42,12,-42,18,-42,16,-42,23,-42,22,-42,17,-42,19,-42,35,-42,32,-42,30,-42,21,-42}));
    AddState(45,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,46,-18,88}));
    AddState(46,new State(new int[]{40,-43,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,-43,45,-43,46,-43,47,-43,48,-43,49,-43,41,-43,43,-43,42,-43,36,-43,12,-43,18,-43,16,-43,23,-43,22,-43,17,-43,19,-43,35,-43,32,-43,30,-43,21,-43}));
    AddState(47,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,48,-18,88}));
    AddState(48,new State(new int[]{40,-44,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,-44,45,-44,46,-44,47,-44,48,-44,49,-44,41,-44,43,-44,42,-44,36,-44,12,-44,18,-44,16,-44,23,-44,22,-44,17,-44,19,-44,35,-44,32,-44,30,-44,21,-44}));
    AddState(49,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,50,-18,88}));
    AddState(50,new State(new int[]{40,-45,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,-45,45,-45,46,-45,47,-45,48,-45,49,-45,41,-45,43,-45,42,-45,36,-45,12,-45,18,-45,16,-45,23,-45,22,-45,17,-45,19,-45,35,-45,32,-45,30,-45,21,-45}));
    AddState(51,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,52,-18,88}));
    AddState(52,new State(new int[]{40,-46,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,-46,43,53,42,-46,36,-46,12,-46,18,-46,16,-46,23,-46,22,-46,17,-46,19,-46,35,-46,32,-46,30,-46,21,-46}));
    AddState(53,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,54,-18,88}));
    AddState(54,new State(new int[]{40,-47,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,-47,43,-47,42,-47,36,-47,12,-47,18,-47,16,-47,23,-47,22,-47,17,-47,19,-47,35,-47,32,-47,30,-47,21,-47}));
    AddState(55,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,56,-18,88}));
    AddState(56,new State(new int[]{40,-48,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,-48,43,53,42,-48,36,-48,12,-48,18,-48,16,-48,23,-48,22,-48,17,-48,19,-48,35,-48,32,-48,30,-48,21,-48}));
    AddState(57,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,58,-18,88}));
    AddState(58,new State(-37));
    AddState(59,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,60,-18,88}));
    AddState(60,new State(new int[]{40,-38,31,24,50,-38,51,-38,55,31,52,33,53,35,54,37,44,-38,45,-38,46,-38,47,-38,48,-38,49,-38,41,-38,43,-38,42,-38,36,-38,12,-38,18,-38,16,-38,23,-38,22,-38,17,-38,19,-38,35,-38,32,-38,30,-38,21,-38}));
    AddState(61,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,62,-18,88}));
    AddState(62,new State(-39));
    AddState(63,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,64,-18,88}));
    AddState(64,new State(new int[]{30,65,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(65,new State(-49));
    AddState(66,new State(new int[]{29,67}));
    AddState(67,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,68,-18,88}));
    AddState(68,new State(new int[]{30,69,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(69,new State(-50));
    AddState(70,new State(new int[]{29,71,17,-54,19,-54,40,-54,31,-54,50,-54,51,-54,55,-54,52,-54,53,-54,54,-54,44,-54,45,-54,46,-54,47,-54,48,-54,49,-54,41,-54,43,-54,42,-54,18,-54,35,-54,36,-54,12,-54,16,-54,23,-54,22,-54,32,-54,30,-54,21,-54}));
    AddState(71,new State(new int[]{30,74,51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-17,72,-15,75,-18,88}));
    AddState(72,new State(new int[]{30,73}));
    AddState(73,new State(-51));
    AddState(74,new State(-52));
    AddState(75,new State(new int[]{35,76,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55,30,-64}));
    AddState(76,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-17,77,-15,75,-18,88}));
    AddState(77,new State(-63));
    AddState(78,new State(new int[]{3,93,5,94},new int[]{-7,79,-9,92}));
    AddState(79,new State(new int[]{31,80,6,91}));
    AddState(80,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,81,-18,88}));
    AddState(81,new State(new int[]{32,82,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(82,new State(-53));
    AddState(83,new State(-55));
    AddState(84,new State(-56));
    AddState(85,new State(-57));
    AddState(86,new State(-58));
    AddState(87,new State(-59));
    AddState(88,new State(-60));
    AddState(89,new State(new int[]{27,89,40,-62,31,-62,50,-62,51,-62,55,-62,52,-62,53,-62,54,-62,44,-62,45,-62,46,-62,47,-62,48,-62,49,-62,41,-62,43,-62,42,-62,36,-62,12,-62,18,-62,16,-62,23,-62,22,-62,17,-62,19,-62,35,-62,32,-62,30,-62,21,-62},new int[]{-18,90}));
    AddState(90,new State(-61));
    AddState(91,new State(-8));
    AddState(92,new State(-9));
    AddState(93,new State(-10));
    AddState(94,new State(-11));
    AddState(95,new State(new int[]{40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55,18,-68,36,-21,12,-21,16,-21,23,-21,22,-21}));
    AddState(96,new State(new int[]{29,71,38,97,40,-54,31,-54,50,-54,51,-54,55,-54,52,-54,53,-54,54,-54,44,-54,45,-54,46,-54,47,-54,48,-54,49,-54,41,-54,43,-54,42,-54,36,-54,12,-54,18,-54,16,-54,23,-54,22,-54}));
    AddState(97,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-10,98,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(98,new State(-27));
    AddState(99,new State(-18));
    AddState(100,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,101,-18,88}));
    AddState(101,new State(new int[]{17,102,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(102,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,103,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(103,new State(new int[]{12,104}));
    AddState(104,new State(-69));
    AddState(105,new State(-19));
    AddState(106,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,107,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(107,new State(new int[]{16,108}));
    AddState(108,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,109,-18,88}));
    AddState(109,new State(new int[]{40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55,36,-70,12,-70,16,-70,23,-70,22,-70}));
    AddState(110,new State(-20));
    AddState(111,new State(-71));
    AddState(112,new State(new int[]{12,113,23,114,22,146}));
    AddState(113,new State(-75));
    AddState(114,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-25,115,-15,143,-18,88}));
    AddState(115,new State(new int[]{23,116,12,-76,22,-76}));
    AddState(116,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,117,-18,88}));
    AddState(117,new State(new int[]{21,118,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(118,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,119,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(119,new State(-80));
    AddState(120,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,121,-18,88}));
    AddState(121,new State(new int[]{21,122,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(122,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,123,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(123,new State(-74));
    AddState(124,new State(-72));
    AddState(125,new State(new int[]{12,126,22,127}));
    AddState(126,new State(-77));
    AddState(127,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,128,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(128,new State(new int[]{12,129}));
    AddState(129,new State(-79));
    AddState(130,new State(-73));
    AddState(131,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89,36,-23,12,-23,16,-23,23,-23,22,-23},new int[]{-15,132,-18,88}));
    AddState(132,new State(new int[]{40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55,36,-22,12,-22,16,-22,23,-22,22,-22}));
    AddState(133,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,134,-18,88}));
    AddState(134,new State(new int[]{40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55,36,-24,12,-24,16,-24,23,-24,22,-24}));
    AddState(135,new State(new int[]{35,136,36,-25,12,-25,16,-25,23,-25,22,-25}));
    AddState(136,new State(new int[]{26,137}));
    AddState(137,new State(new int[]{40,138,35,-83,36,-83,12,-83,16,-83,23,-83,22,-83}));
    AddState(138,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,139,-18,88}));
    AddState(139,new State(new int[]{40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55,35,-82,36,-82,12,-82,16,-82,23,-82,22,-82}));
    AddState(140,new State(-26));
    AddState(141,new State(new int[]{26,142}));
    AddState(142,new State(-28));
    AddState(143,new State(new int[]{21,144,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(144,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,145,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(145,new State(-81));
    AddState(146,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,147,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(147,new State(new int[]{12,148}));
    AddState(148,new State(-78));
    AddState(149,new State(new int[]{51,57,50,59,28,61,29,63,8,66,26,70,7,78,24,83,25,84,14,85,15,86,13,87,27,89},new int[]{-15,150,-18,88}));
    AddState(150,new State(new int[]{17,151,40,22,31,24,50,27,51,29,55,31,52,33,53,35,54,37,44,39,45,41,46,43,47,45,48,47,49,49,41,51,43,53,42,55}));
    AddState(151,new State(new int[]{3,93,5,94,51,57,50,59,28,61,29,63,8,66,26,96,7,78,24,83,25,84,14,85,15,86,13,87,27,89,16,100,17,106,20,120,10,131,9,133,36,140,37,141},new int[]{-6,152,-10,8,-11,11,-19,12,-7,18,-9,92,-15,95,-18,88,-12,99,-13,105,-14,110,-20,111,-23,112,-21,124,-24,125,-22,130,-16,135}));
    AddState(152,new State(new int[]{12,153}));
    AddState(153,new State(-66));
    AddState(154,new State(new int[]{26,164,3,93,5,94},new int[]{-7,155,-9,92}));
    AddState(155,new State(new int[]{26,156,6,91}));
    AddState(156,new State(new int[]{29,157}));
    AddState(157,new State(new int[]{3,93,5,94,30,-14},new int[]{-8,158,-7,160,-9,92}));
    AddState(158,new State(new int[]{30,159}));
    AddState(159,new State(-6));
    AddState(160,new State(new int[]{26,161,6,91}));
    AddState(161,new State(new int[]{35,162,30,-13}));
    AddState(162,new State(new int[]{3,93,5,94,30,-14},new int[]{-8,163,-7,160,-9,92}));
    AddState(163,new State(-12));
    AddState(164,new State(new int[]{29,165}));
    AddState(165,new State(new int[]{3,93,5,94,30,-14},new int[]{-8,166,-7,160,-9,92}));
    AddState(166,new State(new int[]{30,167}));
    AddState(167,new State(-7));

    rules=new Rule[86];
    rules[1]=new Rule(-3, new int[]{-1,2});
    rules[2]=new Rule(-2, new int[]{-1,2});
    rules[3]=new Rule(-1, new int[]{-4,-1});
    rules[4]=new Rule(-1, new int[]{-4});
    rules[5]=new Rule(-4, new int[]{-5,-6,12});
    rules[6]=new Rule(-5, new int[]{11,-7,26,29,-8,30});
    rules[7]=new Rule(-5, new int[]{11,26,29,-8,30});
    rules[8]=new Rule(-7, new int[]{-7,6});
    rules[9]=new Rule(-7, new int[]{-9});
    rules[10]=new Rule(-9, new int[]{3});
    rules[11]=new Rule(-9, new int[]{5});
    rules[12]=new Rule(-8, new int[]{-7,26,35,-8});
    rules[13]=new Rule(-8, new int[]{-7,26});
    rules[14]=new Rule(-8, new int[]{});
    rules[15]=new Rule(-6, new int[]{-10,36,-6});
    rules[16]=new Rule(-6, new int[]{-10});
    rules[17]=new Rule(-10, new int[]{-11});
    rules[18]=new Rule(-10, new int[]{-12});
    rules[19]=new Rule(-10, new int[]{-13});
    rules[20]=new Rule(-10, new int[]{-14});
    rules[21]=new Rule(-10, new int[]{-15});
    rules[22]=new Rule(-10, new int[]{10,-15});
    rules[23]=new Rule(-10, new int[]{10});
    rules[24]=new Rule(-10, new int[]{9,-15});
    rules[25]=new Rule(-10, new int[]{-16});
    rules[26]=new Rule(-10, new int[]{36});
    rules[27]=new Rule(-10, new int[]{26,38,-10});
    rules[28]=new Rule(-10, new int[]{37,26});
    rules[29]=new Rule(-15, new int[]{-15,40,-15});
    rules[30]=new Rule(-15, new int[]{-15,31,-15,32});
    rules[31]=new Rule(-15, new int[]{-15,50,-15});
    rules[32]=new Rule(-15, new int[]{-15,51,-15});
    rules[33]=new Rule(-15, new int[]{-15,55,-15});
    rules[34]=new Rule(-15, new int[]{-15,52,-15});
    rules[35]=new Rule(-15, new int[]{-15,53,-15});
    rules[36]=new Rule(-15, new int[]{-15,54,-15});
    rules[37]=new Rule(-15, new int[]{51,-15});
    rules[38]=new Rule(-15, new int[]{50,-15});
    rules[39]=new Rule(-15, new int[]{28,-15});
    rules[40]=new Rule(-15, new int[]{-15,44,-15});
    rules[41]=new Rule(-15, new int[]{-15,45,-15});
    rules[42]=new Rule(-15, new int[]{-15,46,-15});
    rules[43]=new Rule(-15, new int[]{-15,47,-15});
    rules[44]=new Rule(-15, new int[]{-15,48,-15});
    rules[45]=new Rule(-15, new int[]{-15,49,-15});
    rules[46]=new Rule(-15, new int[]{-15,41,-15});
    rules[47]=new Rule(-15, new int[]{-15,43,-15});
    rules[48]=new Rule(-15, new int[]{-15,42,-15});
    rules[49]=new Rule(-15, new int[]{29,-15,30});
    rules[50]=new Rule(-15, new int[]{8,29,-15,30});
    rules[51]=new Rule(-15, new int[]{26,29,-17,30});
    rules[52]=new Rule(-15, new int[]{26,29,30});
    rules[53]=new Rule(-15, new int[]{7,-7,31,-15,32});
    rules[54]=new Rule(-15, new int[]{26});
    rules[55]=new Rule(-15, new int[]{24});
    rules[56]=new Rule(-15, new int[]{25});
    rules[57]=new Rule(-15, new int[]{14});
    rules[58]=new Rule(-15, new int[]{15});
    rules[59]=new Rule(-15, new int[]{13});
    rules[60]=new Rule(-15, new int[]{-18});
    rules[61]=new Rule(-18, new int[]{27,-18});
    rules[62]=new Rule(-18, new int[]{27});
    rules[63]=new Rule(-17, new int[]{-15,35,-17});
    rules[64]=new Rule(-17, new int[]{-15});
    rules[65]=new Rule(-11, new int[]{-19,18,-15,17,-6,12});
    rules[66]=new Rule(-11, new int[]{-19,18,-15,19,-15,17,-6,12});
    rules[67]=new Rule(-19, new int[]{-7,26,40,-15});
    rules[68]=new Rule(-19, new int[]{-15});
    rules[69]=new Rule(-12, new int[]{16,-15,17,-6,12});
    rules[70]=new Rule(-13, new int[]{17,-6,16,-15});
    rules[71]=new Rule(-14, new int[]{-20});
    rules[72]=new Rule(-14, new int[]{-21});
    rules[73]=new Rule(-14, new int[]{-22});
    rules[74]=new Rule(-23, new int[]{20,-15,21,-6});
    rules[75]=new Rule(-20, new int[]{-23,12});
    rules[76]=new Rule(-24, new int[]{-23,23,-25});
    rules[77]=new Rule(-21, new int[]{-24,12});
    rules[78]=new Rule(-22, new int[]{-23,22,-6,12});
    rules[79]=new Rule(-22, new int[]{-24,22,-6,12});
    rules[80]=new Rule(-25, new int[]{-25,23,-15,21,-6});
    rules[81]=new Rule(-25, new int[]{-15,21,-6});
    rules[82]=new Rule(-16, new int[]{-16,35,26,40,-15});
    rules[83]=new Rule(-16, new int[]{-16,35,26});
    rules[84]=new Rule(-16, new int[]{-7,26,40,-15});
    rules[85]=new Rule(-16, new int[]{-7,26});

    nonTerminals = new string[] {"", "program", "s", "$accept", "function_definition", 
      "function_header", "statement_list", "type", "parameters_list", "primitive_type", 
      "statement", "cycle_to", "while_do", "do_while", "if_set", "expression", 
      "variable_definition_list", "va_list", "string_from_literals", "cycle_to_start", 
      "primitive_if", "switch_if", "alternative_if", "if_clause", "switch_if_sep", 
      "elsif_set", };
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // s -> program, EOF
{

			}
        break;
      case 3: // program -> function_definition, program
{
				L1Program program = (L1Program)value_stack.array[value_stack.top-1].Tag;
				program.AddFunctionToForward((FunctionDefinition)value_stack.array[value_stack.top-2].Tag);
				yyval.Tag = program;
            }
        break;
      case 4: // program -> function_definition
{
				L1Program program = CompilerServices.Program;
				program.AddFunctionToForward((FunctionDefinition)value_stack.array[value_stack.top-1].Tag);
				yyval.Tag = program;
				CompilerServices.Program = program;
            }
        break;
      case 5: // function_definition -> function_header, statement_list, END
{
				FunctionDefinition definition = new FunctionDefinition();
				definition.Header = (FunctionHeader)value_stack.array[value_stack.top-3].Tag;
				definition.Statements = (StatementList)value_stack.array[value_stack.top-2].Tag;
				definition.Location = yyloc;
				yyval.Tag = definition;
            }
        break;
      case 6: // function_header -> DEFINE, type, IDENTIFIER, LP, parameters_list, RP
{
 				FunctionHeader header = new FunctionHeader(value_stack.array[value_stack.top-4].sVal, (VariableType)value_stack.array[value_stack.top-5].Tag);
				List<FunctionParameter> parameters = (List<FunctionParameter>)value_stack.array[value_stack.top-2].Tag;
				foreach (FunctionParameter p in parameters)
				{
					header.AddParameter(p);
				}
				header.Location = yyloc;
				yyval.Tag = header;           
            }
        break;
      case 7: // function_header -> DEFINE, IDENTIFIER, LP, parameters_list, RP
{
				FunctionHeader header = new FunctionHeader(value_stack.array[value_stack.top-4].sVal, null);
				List<FunctionParameter> parameters = (List<FunctionParameter>)value_stack.array[value_stack.top-2].Tag;
				foreach (FunctionParameter p in parameters)
				{
					header.AddParameter(p);
				}
				header.Location = yyloc;
				yyval.Tag = header;
            }
        break;
      case 8: // type -> type, ARRAY
{
				VariableType type = new VariableType(VariableTypeEnum.Array, (VariableType)value_stack.array[value_stack.top-2].Tag);
				yyval.Tag = type;
            }
        break;
      case 9: // type -> primitive_type
{
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 10: // primitive_type -> INT
{
				VariableType type = new VariableType(VariableTypeEnum.Integer);
				yyval.Tag = type;
            }
        break;
      case 11: // primitive_type -> BOOL
{
 				VariableType type = new VariableType(VariableTypeEnum.Bool);
 				yyval.Tag = type;
            }
        break;
      case 12: // parameters_list -> type, IDENTIFIER, SEMI, parameters_list
{
				List<FunctionParameter> list = (List<FunctionParameter>)value_stack.array[value_stack.top-1].Tag;
				FunctionParameter parameter = new FunctionParameter(value_stack.array[value_stack.top-3].sVal, (VariableType)value_stack.array[value_stack.top-4].Tag);
				parameter.Location = yyloc;
				list.Insert(0, parameter);
				yyval.Tag = list;
			}
        break;
      case 13: // parameters_list -> type, IDENTIFIER
{
				List<FunctionParameter> list = new List<FunctionParameter>();
				FunctionParameter parameter = new FunctionParameter(value_stack.array[value_stack.top-1].sVal, (VariableType)value_stack.array[value_stack.top-2].Tag);
				parameter.Location = yyloc;
				list.Insert(0, parameter);
				yyval.Tag = list;
            }
        break;
      case 14: // parameters_list -> /* empty */
{
				yyval.Tag = new List<FunctionParameter>();
			}
        break;
      case 15: // statement_list -> statement, COMMA, statement_list
{
				StatementList statementList = (StatementList)value_stack.array[value_stack.top-1].Tag;
				statementList.AddForward((Statement)value_stack.array[value_stack.top-3].Tag);
				yyval.Tag = statementList;
            }
        break;
      case 16: // statement_list -> statement
{
				StatementList statementList = new StatementList();
				statementList.AddForward((Statement)value_stack.array[value_stack.top-1].Tag);
				yyval.Tag = statementList;
            }
        break;
      case 17: // statement -> cycle_to
{	
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 18: // statement -> while_do
{
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 19: // statement -> do_while
{
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 20: // statement -> if_set
{
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 21: // statement -> expression
{
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 22: // statement -> RETURN, expression
{
            	ReturnStatement statement = new ReturnStatement();
            	statement.Expression = (Expression)value_stack.array[value_stack.top-1].Tag;
            	statement.Location = yyloc;
				yyval.Tag = statement;
            }
        break;
      case 23: // statement -> RETURN
{
				ReturnStatement statement = new ReturnStatement();
				statement.Location = yyloc;
				yyval.Tag = statement;
            }
        break;
      case 24: // statement -> ASSERT, expression
{
                AssertStatement statement = new AssertStatement();
            	statement.Expression = (Expression)value_stack.array[value_stack.top-1].Tag;
            	statement.Location = yyloc;
				yyval.Tag = statement;
            }
        break;
      case 25: // statement -> variable_definition_list
{
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 26: // statement -> COMMA
{
				yyval.Tag = Statement.Dummy;
            }
        break;
      case 27: // statement -> IDENTIFIER, PERIPERI, statement
{
            	yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            	((Statement)yyval.Tag).Location = yyloc;
            	((Statement)yyval.Tag).Label = value_stack.array[value_stack.top-3].sVal;
            }
        break;
      case 28: // statement -> GOTO, IDENTIFIER
{
            	GotoStatement statement = new GotoStatement();
            	statement.GoTo = value_stack.array[value_stack.top-1].sVal;
            	statement.Location = yyloc;
            	yyval.Tag = statement;
            }
        break;
      case 29: // expression -> expression, ASSIGN, expression
{ 	
                	Expression expr = new Expression();
					expr.OpType = OperationType.Assign;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 30: // expression -> expression, LAP, expression, RAP
{ 
                    Expression expr = new Expression();
					expr.OpType = OperationType.ArrayAccess;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-4].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-2].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 31: // expression -> expression, PLUS, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Plus;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 32: // expression -> expression, MINUS, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Minus;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 33: // expression -> expression, POWER, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Power;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 34: // expression -> expression, MULT, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Mult;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 35: // expression -> expression, DIV, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Div;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 36: // expression -> expression, MOD, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Mod;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 37: // expression -> MINUS, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.UMinus;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.RightNode = null;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 38: // expression -> PLUS, expression
{ 
					//TODO: ïðîâåðêà íà íå Bool
					yyval.Tag = value_stack.array[value_stack.top-1].Tag;
                }
        break;
      case 39: // expression -> NOT, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.UNot;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.RightNode = null;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 40: // expression -> expression, EQ, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Equals;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 41: // expression -> expression, NEQ, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.NotEquals;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 42: // expression -> expression, GR, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Gr;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 43: // expression -> expression, GREQ, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Greq;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 44: // expression -> expression, LE, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Le;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 45: // expression -> expression, LEEQ, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Leeq;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 46: // expression -> expression, OR, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Or;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 47: // expression -> expression, AND, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.And;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 48: // expression -> expression, XOR, expression
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.Xor;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-3].Tag;
					expr.RightNode = (Expression)value_stack.array[value_stack.top-1].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 
                }
        break;
      case 49: // expression -> LP, expression, RP
{ 
					yyval.Tag = value_stack.array[value_stack.top-2].Tag;
                }
        break;
      case 50: // expression -> ARRAY_LENGTH, LP, expression, RP
{
					Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.ArrayLength;
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-2].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 								
				}
        break;
      case 51: // expression -> IDENTIFIER, LP, va_list, RP
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.FunctionCall;
					expr.Value = value_stack.array[value_stack.top-4].sVal;
					expr.VAList = (VAList)value_stack.array[value_stack.top-2].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 					
                }
        break;
      case 52: // expression -> IDENTIFIER, LP, RP
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.FunctionCall;
					expr.Value = value_stack.array[value_stack.top-3].sVal;
					expr.VAList = new VAList();
					expr.Location = yyloc;
					yyval.Tag = expr; 					
                }
        break;
      case 53: // expression -> NEW, type, LAP, expression, RAP
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.ArrayAlloc;
					expr.Value = value_stack.array[value_stack.top-4].Tag;
					expr.ResultType = new VariableType(VariableTypeEnum.Array, (VariableType)value_stack.array[value_stack.top-4].Tag);
					expr.LeftNode = (Expression)value_stack.array[value_stack.top-2].Tag;
					expr.Location = yyloc;
					yyval.Tag = expr; 						
                }
        break;
      case 54: // expression -> IDENTIFIER
{ 
					//Ñþäà íóæíî áóäåò åùå äîáàâèòü òèï ïåðåìåííîé (äëÿ ñåìàíòè÷åñêîãî àíàëèçà)
					Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.VariableAccess;
					expr.Value = value_stack.array[value_stack.top-1].sVal;
					expr.Location = yyloc;
					yyval.Tag = expr; 						
                }
        break;
      case 55: // expression -> INTEGER
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.Constant;
					expr.IntValue = value_stack.array[value_stack.top-1].iVal;
					expr.ResultType = VariableType.IntType;
					expr.Location = yyloc;
					yyval.Tag = expr; 	                
                }
        break;
      case 56: // expression -> CHAR_LITERAL
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.Constant;
					expr.IntValue = value_stack.array[value_stack.top-1].iVal;
					expr.ResultType = VariableType.IntType;
					expr.Location = yyloc;
					yyval.Tag = expr;                 
                }
        break;
      case 57: // expression -> T
{ 
					Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.Constant;
					expr.BoolValue = true;
					expr.ResultType = VariableType.BoolType;
					expr.Location = yyloc;
					yyval.Tag = expr;                 
                }
        break;
      case 58: // expression -> F
{ 
 					Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.Constant;
					expr.BoolValue = false;
					expr.ResultType = VariableType.BoolType;
					expr.Location = yyloc;
					yyval.Tag = expr;                
                }
        break;
      case 59: // expression -> NULL
{ 
                 	Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.Constant;
					expr.Value = null;
					expr.ResultType = VariableType.NullType;
					expr.Location = yyloc;
					yyval.Tag = expr;     
                }
        break;
      case 60: // expression -> string_from_literals
{
                 	Expression expr = new Expression();
					expr.OpType = OperationType.None;
					expr.IsLeaf = true;
					expr.LeafType = ExpressionLeafType.Constant;
					expr.Value = value_stack.array[value_stack.top-1].sVal;
					expr.ResultType = new VariableType(VariableTypeEnum.Array, VariableType.IntType);
					expr.Location = yyloc;
					yyval.Tag = expr;     					 
                }
        break;
      case 61: // string_from_literals -> STRING_LITERAL, string_from_literals
{
					yyval.sVal = value_stack.array[value_stack.top-2].sVal + value_stack.array[value_stack.top-1].sVal;
                }
        break;
      case 62: // string_from_literals -> STRING_LITERAL
{
					yyval.sVal = value_stack.array[value_stack.top-1].sVal;
                }
        break;
      case 63: // va_list -> expression, SEMI, va_list
{
					yyval.Tag = value_stack.array[value_stack.top-1].Tag;
					((VAList)yyval.Tag).AddForward((Expression)value_stack.array[value_stack.top-3].Tag);
                }
        break;
      case 64: // va_list -> expression
{
					VAList list = new VAList();
					list.Add((Expression)value_stack.array[value_stack.top-1].Tag);
					yyval.Tag = list;
                }
        break;
      case 65: // cycle_to -> cycle_to_start, TO, expression, DO, statement_list, END
{
				CycleStatement cycle = (CycleStatement)value_stack.array[value_stack.top-6].Tag;
				cycle.EndValue = (Expression)value_stack.array[value_stack.top-4].Tag;
				cycle.Statements = (StatementList)value_stack.array[value_stack.top-2].Tag;
				cycle.Location = yyloc;
				yyval.Tag = cycle;
            }
        break;
      case 66: // cycle_to -> cycle_to_start, TO, expression, STEP, expression, DO, 
               //             statement_list, END
{
				CycleStatement cycle = (CycleStatement)value_stack.array[value_stack.top-8].Tag;
				cycle.EndValue = (Expression)value_stack.array[value_stack.top-6].Tag;
				cycle.Step = (Expression)value_stack.array[value_stack.top-4].Tag;
				cycle.Statements = (StatementList)value_stack.array[value_stack.top-2].Tag;
				cycle.Location = yyloc;
				yyval.Tag = cycle;
            }
        break;
      case 67: // cycle_to_start -> type, IDENTIFIER, ASSIGN, expression
{
				CycleStatement cycle = new CycleStatement();
				cycle.VariableType = (VariableType)value_stack.array[value_stack.top-4].Tag;
				cycle.DeclareVariable = (string)value_stack.array[value_stack.top-3].sVal;
				cycle.Init = (Expression)value_stack.array[value_stack.top-1].Tag;
				yyval.Tag = cycle;
            }
        break;
      case 68: // cycle_to_start -> expression
{
				CycleStatement cycle = new CycleStatement();
				cycle.Init = (Expression)value_stack.array[value_stack.top-1].Tag;
				yyval.Tag = cycle;				
            }
        break;
      case 69: // while_do -> WHILE, expression, DO, statement_list, END
{
				WhileDoStatement statement = new WhileDoStatement();
				statement.Condition = (Expression)value_stack.array[value_stack.top-4].Tag;
				statement.Statements = (StatementList)value_stack.array[value_stack.top-2].Tag;
				yyval.Tag = statement;
            }
        break;
      case 70: // do_while -> DO, statement_list, WHILE, expression
{
            	DoWhileStatement statement = new DoWhileStatement();
				statement.Condition = (Expression)value_stack.array[value_stack.top-1].Tag;
				statement.Statements = (StatementList)value_stack.array[value_stack.top-3].Tag;
				yyval.Tag = statement;
            }
        break;
      case 71: // if_set -> primitive_if
{
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 72: // if_set -> switch_if
{
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 73: // if_set -> alternative_if
{
				yyval.Tag = value_stack.array[value_stack.top-1].Tag;
            }
        break;
      case 74: // if_clause -> IF, expression, THEN, statement_list
{
				IfClause clause = new IfClause();
				clause.Condition = (Expression)value_stack.array[value_stack.top-3].Tag;
				clause.Statements = (StatementList)value_stack.array[value_stack.top-1].Tag;
				clause.Location = yyloc;
				yyval.Tag = clause;
            }
        break;
      case 75: // primitive_if -> if_clause, END
{
				IfStatement statement = new IfStatement();
				statement.Clauses.Add((IfClause)value_stack.array[value_stack.top-2].Tag);
				yyval.Tag = statement;
            }
        break;
      case 76: // switch_if_sep -> if_clause, ELSIF, elsif_set
{
				IfStatement statement = new IfStatement();
				statement.Clauses.Add((IfClause)value_stack.array[value_stack.top-3].Tag);
				statement.Clauses.AddRange((IfClauseList)value_stack.array[value_stack.top-1].Tag);
				yyval.Tag = statement;
            }
        break;
      case 77: // switch_if -> switch_if_sep, END
{
				yyval.Tag = value_stack.array[value_stack.top-2].Tag; 
            }
        break;
      case 78: // alternative_if -> if_clause, ELSE, statement_list, END
{
				IfStatement statement = new IfStatement();
				statement.Clauses.Add((IfClause)value_stack.array[value_stack.top-4].Tag);
				statement.AlternativeStatements = (StatementList)value_stack.array[value_stack.top-2].Tag;
				yyval.Tag = statement;
				
            }
        break;
      case 79: // alternative_if -> switch_if_sep, ELSE, statement_list, END
{
				IfStatement statement = (IfStatement)value_stack.array[value_stack.top-4].Tag;
				statement.AlternativeStatements = (StatementList)value_stack.array[value_stack.top-2].Tag;
				yyval.Tag = statement;
            }
        break;
      case 80: // elsif_set -> elsif_set, ELSIF, expression, THEN, statement_list
{
				IfClauseList clauseList = (IfClauseList)value_stack.array[value_stack.top-5].Tag;
				IfClause clause = new IfClause();
				clauseList.Add(clause);
				clause.Condition = (Expression)value_stack.array[value_stack.top-3].Tag;
				clause.Statements = (StatementList)value_stack.array[value_stack.top-1].Tag;
				yyval.Tag = clauseList;
            }
        break;
      case 81: // elsif_set -> expression, THEN, statement_list
{
				IfClauseList clauseList = new IfClauseList();
				IfClause clause = new IfClause();
				clauseList.Add(clause);
				clause.Condition = (Expression)value_stack.array[value_stack.top-3].Tag;
				clause.Statements = (StatementList)value_stack.array[value_stack.top-1].Tag;
				yyval.Tag = clauseList;
            }
        break;
      case 82: // variable_definition_list -> variable_definition_list, SEMI, IDENTIFIER, ASSIGN, 
               //                             expression
{
				VariableDefinitionList list = (VariableDefinitionList)value_stack.array[value_stack.top-5].Tag;
				VariableSymbol symbol = new VariableSymbol();
				symbol.VariableType = list.Definitions[0].VariableType;
				symbol.Name = value_stack.array[value_stack.top-3].sVal;
				symbol.InitExpression = (Expression)value_stack.array[value_stack.top-1].Tag;
				symbol.Location = yyloc;
				list.Add(symbol);
				yyval.Tag = list;  				
            }
        break;
      case 83: // variable_definition_list -> variable_definition_list, SEMI, IDENTIFIER
{
 				VariableDefinitionList list = (VariableDefinitionList)value_stack.array[value_stack.top-3].Tag;
				VariableSymbol symbol = new VariableSymbol();
				symbol.VariableType = list.Definitions[0].VariableType;
				symbol.Name = value_stack.array[value_stack.top-1].sVal;
				symbol.Location = yyloc;
				list.Add(symbol);
				yyval.Tag = list;            
            }
        break;
      case 84: // variable_definition_list -> type, IDENTIFIER, ASSIGN, expression
{
				VariableDefinitionList list = new VariableDefinitionList();
				VariableSymbol symbol = new VariableSymbol();
				symbol.VariableType = (VariableType)value_stack.array[value_stack.top-4].Tag;
				symbol.Name = value_stack.array[value_stack.top-3].sVal;
				symbol.InitExpression = (Expression)value_stack.array[value_stack.top-1].Tag;
				symbol.Location = yyloc;
				list.Add(symbol);
				yyval.Tag = list;            
            }
        break;
      case 85: // variable_definition_list -> type, IDENTIFIER
{
				VariableDefinitionList list = new VariableDefinitionList();
				VariableSymbol symbol = new VariableSymbol();
				symbol.VariableType = (VariableType)value_stack.array[value_stack.top-2].Tag;
				symbol.Name = value_stack.array[value_stack.top-1].sVal;
				symbol.Location = yyloc;
				list.Add(symbol);
				yyval.Tag = list;
            }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString())
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
